### ISSUE TITLE
Shoutcloud integration

### ISSUE THREAD

**Issue by bmonteirog** [bmonteirog/foaas-php-client#2]
Integrate the client with [Shoutcloud](http://shoutcloud.io/). Maybe as an eloquent method, like `->shout()`.
Just using `strtoupper()` is definitely NOT ALLOWED, as is clearly not enterprisey enough. :laughing:

**Comment by joefearnley** [comment]
I could grab this one. Are you thinking something like this?

`echo $fuck->shout()->me('Myself');`

**Comment by joefearnley** [comment]
Looks like a couple of the tests are broken, I can fix those as well.

**Comment by bmonteirog** [comment]
Of course, @joefearnley feel free to send a PR! :sunglasses:  Thanks!
